name: build executable
on:
  push:
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/**"
      - "*.md"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Install Autoit
        run: |
          Invoke-WebRequest -Uri https://www.autoitscript.com/cgi-bin/getfile.pl?autoit3/autoit-v3-setup.exe -OutFile autoit-v3-setup.exe
          ./autoit-v3-setup.exe /S
      - name: Compile
        run: |
          cd C:\"Program Files (x86)"\AutoIt3\Aut2Exe
          cd LinuxLiveUSBCreator
          $ver= git rev-list --count HEAD
          cd ..
          mkdir build
          C:\"Program Files (x86)"\AutoIt3\Aut2Exe/Aut2exe.exe /in aoe2de-matchfound.au3 /out build\aoe2de-matchfound-1.0$ver.exe /nopack /icon icon.ico /comp 4 /x86
          Start-Sleep -s 10
          Copy-Item 14.wav -Destination build
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: aoe2de-matchfound
          path: |
            build/
            !build/.gitkeep
          if-no-files-found: error
