name: build
on:
  push:
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/**"
      - "*.md"

jobs:
  build:
    runs-on: windows-latest
    steps:

      - name: Cache Autoit
        id: cache-autoit
        uses: actions/cache@v3
        with:
          path: C:\Program Files (x86)\AutoIt3\Aut2Exe
          key: ${{ runner.os }}-autoit

      - name: Install Autoit
        if: steps.cache-autoit.outputs.cache-hit != 'true'
        run: |
          Invoke-WebRequest -Uri https://www.autoitscript.com/cgi-bin/getfile.pl?autoit3/autoit-v3-setup.exe -OutFile autoit-v3-setup.exe
          ./autoit-v3-setup.exe /S

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Compile
        run: |
          ls
          C:\"Program Files (x86)"\AutoIt3\Aut2Exe\Aut2exe.exe /in aoe2de-matchfound.au3 /out build\aoe2de-matchfound.exe /nopack /icon icon.ico /comp 0 /x86
          Start-Sleep -s 10
          Copy-Item 14.wav -Destination build
          ls build

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: aoe2de-matchfound
          path: |
            build/
            !build/.gitkeep
          if-no-files-found: error

  virustotal:
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Retrieve executale file from artifact
        uses: actions/download-artifact@v3
        with:
          name: aoe2de-matchfound
          path: .

      - name: test
        run: ls -lah

      - name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v3
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          files: |
            aoe2de-matchfound.exe
