name: virustotal check
on:
  workflow_call:

jobs:
  virustotal:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve executale file from artifact
        uses: actions/download-artifact@v3
        with:
          name: aoe2de-matchfound
          path: .

      - name: Check file exists
        run: ls -lah

      - name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v3
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          files: |
            aoe2de-matchfound.exe
